### ISSUE TITLE
[PE-D][Tester D] Improper spacing for em dash

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T14-4/tp#232]
No spacing is taken to be the more standard professional usage

![Maximize your productivity, minimize your response time, and amplify your sales performance..png](https://raw.githubusercontent.com/siriousguy/ped/main/files/874392d2-1acc-4e47-bb20-67b1486bacba.png)￼

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: siriousguy/ped#3

**Comment by colinhia** [comment]
Thanks for submitting this bug report!

Our team dispute the stated format as a bug, due to the following reasons:

We found that generally, spacing before and after an em dash is considered a stylistic choice, and there does not seem to be any set conventions. Certain conventions also seem to differ based on contexts, such as British English, or American English.

Thank you once again for submitting a bug report!

**Comment by colinhia** [comment]
Thanks for submitting this bug report!

Our team dispute the stated format as a bug, due to the following reasons:

We found that generally, spacing before and after an em dash is considered a stylistic choice, and there does not seem to be any set conventions. Certain conventions also seem to differ based on contexts, such as British English, or American English.

Thank you once again for submitting a bug report!
