### ISSUE TITLE
[PE-D][Tester D]  Behavior for close differs from normal expectations

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T14-4/tp#249]
Good that typing 'y' or 'n' returns 'Unknown command.
Please type 'help' to see the list of available commands.'.

However, typing 'close' when there was no prior viewing results in 'Detailed view closed.' to be displayed when a more proper response can be 'No client viewed.' etc. 

![Screenshot 2024-11-08 at 4.35.26 PM.png](https://raw.githubusercontent.com/siriousguy/ped/main/files/7bb85dec-29ef-4a37-8806-a1f66f034a90.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: siriousguy/ped#11

**Comment by iamdiluxedbutcooler** [comment]
Thank you for the feedback regarding the close command behavior.

This suggestion falls under potential enhancements rather than critical fixes, as:
1. The current behavior doesn't cause any functional issues - the command still 
   operates correctly without causing system errors or data inconsistencies
2. The feedback message, while not ideal, doesn't mislead users into incorrect 
   actions - it accurately reflects that no detail panel is open
3. The change would be purely cosmetic, improving user experience but not 
   affecting system integrity or core functionality

We will document this feedback under "Future Enhancements" in our Developer Guide 
for consideration in future releases.
